[package]
name = "qrcode"
version = "0.1.0"
authors = [
    "Матвей Т <https://matveit.dev>"
]
edition = "2021"

[[bin]]
name = "generate-qrcodes"
path = "../bins/generate_qrcodes.rs"

[lib]
name = "qrcode"
path = "lib.rs"

[dependencies]
qrcode-core = { path = "./qrcode-core" }
